"""Immutable, OCaml-inspired functional wrapper for IBM Quantum and Aer."""

from .backend import AER_METHODS, Aer, FakeIBMBackend, IBMHardware
from .api import (
    compile_circuit_batch_sync,
    draw_transpiled_circuit_layout_sync,
    run_async,
    run_sample_batch_sync,
    run_sync,
)
from .circuit import (
    CX,
    H,
    MultiControlledRZ,
    MultiControlledXXPlusYY,
    RZ,
    X,
    Circuit,
    ClassicallyControlledXXPlusYY,
    ControlledXXPlusYY,
    Measure,
    Reset,
    SaveDensityMatrix,
    XXPlusYY,
    classically_controlled_xx_plus_yy,
    controlled_xx_plus_yy,
    cx,
    empty,
    h,
    measure,
    multi_controlled_rz,
    multi_controlled_xx_plus_yy,
    pipe,
    reset,
    rz,
    save_density_matrix,
    x,
    xx_plus_yy,
)
from .compile import CompilationMetrics, CompilerConfig
from .execute import (
    ExecutionFailure,
    ExecutionPlan,
    DensityMatrixResult,
    Estimate,
    EstimateResult,
    ExpectationValue,
    Sample,
    SampleResult,
    SimulateDensityMatrices,
    ValidationFailure,
    counts_dict,
    estimates_dict,
    execution_plan,
    validate,
    snapshots_dict,
)
from .functional import concat_map, exists, filter_map, fold_left, map_tuple, scan_left
from .observable import (
    Observable,
    PauliFactor,
    PauliTerm,
    observable,
    pauli,
    pauli_term,
)
from .result import Err, Ok
from .runtime import IBMAccount, RuntimeEnvironment
from .utils import load_ibm_account
from .interpreters.qiskit import draw_circuit


__all__ = (
    "AER_METHODS",
    "Aer",
    "CX",
    "Circuit",
    "ClassicallyControlledXXPlusYY",
    "CompilerConfig",
    "CompilationMetrics",
    "Err",
    "Estimate",
    "EstimateResult",
    "ExecutionFailure",
    "ExecutionPlan",
    "ExpectationValue",
    "FakeIBMBackend",
    "DensityMatrixResult",
    "H",
    "IBMAccount",
    "IBMHardware",
    "Measure",
    "MultiControlledRZ",
    "MultiControlledXXPlusYY",
    "Ok",
    "Observable",
    "PauliFactor",
    "PauliTerm",
    "RuntimeEnvironment",
    "Sample",
    "SampleResult",
    "SimulateDensityMatrices",
    "RZ",
    "Reset",
    "SaveDensityMatrix",
    "X",
    "XXPlusYY",
    "ControlledXXPlusYY",
    "ValidationFailure",
    "counts_dict",
    "concat_map",
    "classically_controlled_xx_plus_yy",
    "compile_circuit_batch_sync",
    "controlled_xx_plus_yy",
    "cx",
    "draw_circuit",
    "draw_transpiled_circuit_layout_sync",
    "empty",
    "estimates_dict",
    "exists",
    "execution_plan",
    "filter_map",
    "fold_left",
    "h",
    "load_ibm_account",
    "map_tuple",
    "measure",
    "multi_controlled_rz",
    "multi_controlled_xx_plus_yy",
    "observable",
    "pauli",
    "pauli_term",
    "pipe",
    "run_async",
    "run_sample_batch_sync",
    "run_sync",
    "reset",
    "rz",
    "save_density_matrix",
    "scan_left",
    "snapshots_dict",
    "validate",
    "x",
    "xx_plus_yy",
)
